### ISSUE TITLE
OpenCart 3.x

### ISSUE THREAD

**Issue by praad** [loadkpi/oc2_minimum_order_amount#1]
Hello, 

Can I help you to make the OpenCart 3.x version of this module? Or can you update it pls?
Thanks

**Comment by loadkpi** [comment]
Sure, I would appreciate the help!

**Comment by condor2** [comment]
https://github.com/condor2/oc_minimum_order_amount/releases/tag/0.3

**Comment by loadkpi** [comment]
@condor2 could you create pull request?
