### ISSUE TITLE
Translation in other languages

### ISSUE THREAD

**Issue by CDS-IT** [loadkpi/oc2_minimum_order_amount#3]
Hello,
Your extension is very nice, it is possible to translate the front end message in other languages ? which files can be edited  for translation ?
Thank you

**Comment by condor2** [comment]
This file
https://github.com/loadkpi/oc2_minimum_order_amount/blob/master/3.0.x.x/upload/admin/language/en-gb/extension/module/minimal_order_amount.php

**Comment by loadkpi** [comment]
yes it's correct file, you can change it directly on your Opencart. Also PR is welcome to create something like multi-language feature
